config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :users do
    resource :profile
  end
  patch '/users/:id/verify', :to => 'users#verify'
  get '/about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Us</h1>
    
    <br>
    
    <div class="well">
        <h4>We are DevMatch. Our company focuses on creating an exclusive community
        for developers, investors, and entrepreneurs to meet. 
        </h4>
        
        <br>
        
        <h4>
            At least...that's what this page would say if this were a real startup 
            company's website. In reality, I created this website with the help of 
            <a href="https://upskillcourses.com/courses/essential-web-developer-course/">
                the following tutorial
            </a>
            in order to further my web development skills. The website was built with
            HTML5, CSS3/SCSS, and JavaScript utilizing the Ruby on Rails framework.
        </h4>
        
        <br>
        
        <h4>User authentication is handled through Devise. I have no access to 
        passwords in the database. E-commerce/subscriptions are handled through
        Stripe; however, if you sign up for a pro account, you <strong>will not</strong>
        get billed, and I have no access to payment information. Feel free to sign up
        for a pro account using fake credit card details in order to view all
        site functionality.</h4>
    </div>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
    <h1>Welcome to DevMatch</h1>
    <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>

<div class="container home-signup-links">
    <div class="row">
    
        <% if user_signed_in? %>
        
            <div class="col-md-6">
                <div class="well">
                    <h2 class="text-center"><i class="fa fa-user"></i> Your Profile</h2>
                    
                    <br>
                    
                    <% if current_user.profile %>
                        <%= link_to edit_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' do %>
                            <i class="fa fa-edit"></i> Edit your profile
                        <% end %>
                        
                        <br>
                        
                        <%= link_to user_path(id: current_user.id), class: 'btn btn-default btn-lg btn-block' do %>
                            <i class="fa fa-eye"></i> View your profile
                        <% end %>
                    <% else %>
                        <p class="text-center">Create your profile so that you can share your information with the community.</p>
                        <%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id), class: 'btn btn-default btn-lg btn-block' %>
                    <% end %>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="well">
                    <h2 class="text-center"><i class="fa fa-group"></i> The Community</h2>
                    <p class="text-center">Visit the community to meet other developers, entrepreneurs, and investors!</p>
                    
                    <%= link_to users_path, class: 'btn btn-default btn-lg btn-block' do %>
                        Visit the community <i class="fa fa-arrow-circle-right"></i>
                    <% end %>
                </div>
            </div>
        
        <% else %>
            <div class="col-md-6">
                <div class="well">
                    <h2 class="text-center">Basic Membership</h2>
                    <h4 class="text-center">Sign up for free and get basic access to the community.</h4>
                    <br>
                    <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="well">
                    <h2 class="text-center">Pro Membership</h2>
                    <h4 class="text-center">Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
                    <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
                </div>
            </div>
        <% end %>
    </div>
    
    
</div>