config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  resources :users do
    resource :profile
  end
  patch '/users/:id/verify', :to => 'users#verify'
  get '/about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link rel="preconnect" href="//fonts.gstatic.com">
    <link href="//fonts.googleapis.com/css2?family=Open+Sans:wght@400;700;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'http://js.stripe.com/v2/', type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <script src='https://www.google.com/recaptcha/api.js'></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-group"></i>
            DevMatch
          <% end %>
        </div>
          <div class="collapse navbar-collapse" id="main-nav-collapse">
            <div class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
                    
                    <% if current_user.profile %>
                      <%= image_tag current_user.profile.avatar.url, class: 'avatar-nav-img' %>
                    <% end %>
                <% else %>
                    <%= link_to "Log In", new_user_session_path, class: 'btn btn-default navbar-btn' %>
                <% end %>
            </div>
            
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Community", users_path %></li>
                <li><%= link_to "My Account", edit_user_registration_path %></li>
              <% end %>
              
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Contact Us", new_contact_path %></li>
            </ul>
          </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    <div class="container flash-container">
        <% flash.each do |type, msg| %>
            <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
    </div>
    
    <%= yield %>

  </body>
</html>